### ISSUE TITLE
[BUG]:[Instability of tests when running in 50 workers.]

### ISSUE THREAD

**Issue by sleepmac** [microsoft/playwright-testing-service#114]
**Describe the bug**
Hi. We are facing the problem of running tests in 50 workers.
Earlier we ran tests on a virtual machine in 12 workers. CPU load was 60-80%.
When we run tests in the service in 50 workers, the CPU load is 10-20%. As we can see on the graph.
But when we run the tests through the service, they are very unstable. The application slows down, windows take a long time to open, images are rendered with a long delay. 
The tests are run for three projects Desktop Chrome, Mobile Chrome, Mobile Webkit.
What can be the problem and how can we solve it?

**Expected behavior**
The tests pass. 

**Screenshots**
![26](https://github.com/microsoft/playwright-testing-service/assets/78872550/e581ad86-d1b8-4de2-9b53-de981ae65238)

**Setup information (please complete the following information):**
 - Azure Subscription Id: 45e2e48d-3ff7-465a-a8ab-1c0a8e2fe18b
 - Workspace Name: Uplaywright
 - Browser on which tests are executed (if applicable): Desktop Chrome, iPhone 13, LG Optimus L70
 - Time range (in PST) when the issue was experienced: 2024-06-21T03:38:57.975
 - Playwright Version: 1.44.0
- Client machine OS: linux
- OS requested on Service: linux

**Comment by vvs11** [comment]
Hi @sleepmac
Thanks for reaching out. 
Could you share more information to help us support you better?
1, What is the configuration of the machine that you are using to run the tests?
2. How are you measuring the load times of the application that you are testing?
3. Where is the application under test hosted? Is it public/private?
4. If private, are you using the expose-network setting provided by Playwright?

**Comment by puagarwa** [comment]
Hi @sleepmac Can you help us provide more info into unstable test and application slowness issue you are facing. 

In general, here is possible reasons
- Your APP under test could slow down due to high parallel workers try to access it. in this case, you need to increase resource allocation into app and also check if any throttling.
- Sometime test flakiness or dependency on other tests can cause failures under high parallelism. In this case, we should debug the reason for failure and accordingly fix those.

From the above description, where you mentioned around webapp slowness it seems webapp under test is not behaving good under 50 parallelism load.

**Comment by vvs11** [comment]
Hi @sleepmac, wanted to check with you if you got a chance to try these out?

**Comment by puagarwa** [comment]
HI @sleepmac , Let us know if you got a chance to able to make progress. We could also arrange a working session to go over it if needed.

**Comment by puagarwa** [comment]
Closing the issue for time being, feel free to reopen with more information.
