### ISSUE TITLE
[BUG]:Bad Token

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright-testing-service#132]
Hey guys, I have tried to generate a new token for one of my workspaces, however it is generating a token 
with a length of 7000+ , compared to the previews one of 1400, and that throws an error when you try to save it in a variable group.
Has that changed or is something wrong ?

**Setup information (please complete the following information):**
 - Azure Subscription Id: 84344572-4ab1-87d5-bbdd214cfdac
 - Workspace Name: AcquisitionWorkspace

Thanks

**Comment by imartinflores** [comment]
Hi @puagarwa , thanks.

I just parsed the token and it came as "Invalid Signature" - It looks like it has a very big array of groups [] (Which I am not sure what it is).

Yes, I was able to use the token to run a test on the service. 

The idea is to migrate to Entra ID authentication, however, we are now using a Library in Azure Pipelines and it does not let you save the token as it exceeds the allowed length.

**Comment by puagarwa** [comment]
HI @imartinflores ,
  Thanks for confirming about big array of group[] inside token claims, i doubted the same but wanted to confirm it. 

group[] - is list of all groups user is part of, generally we dont expect user to be part of these many groups but in this case it seems to be the case. 

Coming to solution/mitigation
- We are investigating if its possible to remove or shorten these claims in token to reduce size but it can take up some time.
- i understand that blocking issue here is size limit of azure pipelines variable, is it possible for you to use azure key vault https://learn.microsoft.com/en-us/azure/devops/pipelines/release/azure-key-vault?view=azure-devops&tabs=classic
- Another thing which we can try is ask someone in your team to create token who may have less groups and token size might be small, you can even create a new user and assign it owner/contributor role in playwright workspace resource.
- Best solution here is to move to EntraId which is secure by nature and doesnt require token anymore. since you are using EntraId, its easy to setup https://learn.microsoft.com/en-us/azure/devops/pipelines/release/configure-workload-identity?view=azure-devops&tabs=managed-identity#set-a-workload-identity-service-connection-to-use-managed-identity-authentication 
  - Create Managed identity or service principal in azure
  - Create service connection in azure pipelines
  - Assign role to identity in playwright workspace 

Having said above, we will keep investigate around long size.

**Comment by imartinflores** [comment]
Thanks @puagarwa  I will try either KeyVault or another user to generate the token before moving to EntraID.

Thank you, I think the ticket can be closed then.

**Comment by puagarwa** [comment]
@imartinflores  i will keep it open until you find workable mitigation.

**Comment by imartinflores** [comment]
@puagarwa Is there anything I need to set in Playwright ? should I remove the usage of the token if I already have a service principal configured in azure pipelines and granted access to the workspace ?

**Comment by puagarwa** [comment]
@imartinflores Are you using our package (@azure/microsoft-playwright-testing) or just playwright.service.config.ts file ? for Entra you need to use our package @azure/microsoft-playwright-testing, here is the doc https://learn.microsoft.com/en-us/azure/playwright-testing/quickstart-run-end-to-end-tests?tabs=playwrightcli, 

here is the doc for adding task in yaml for auth https://learn.microsoft.com/en-us/azure/playwright-testing/quickstart-automate-end-to-end-testing?tabs=pipelines

**Comment by imartinflores** [comment]
Thanks @puagarwa , I have installed the package and I am running the tests using one of our service principals who has access granted to AcquisitionWorkspace, however, I am getting this:
```

$ npx playwright test --config=playwright.service.config.js --workers=10 --project=Android_Chrome_Live

Running tests using Microsoft Playwright Testing service.
Error: browserType.connect: WebSocket error: *** 401 Unauthorized
    Call log:
      - <ws connecting> ***
      - 75bce64a-e8e2-4126-b660-102aedc02a23
      - <ws unexpected response> *** 401 Unauthorized
      - <ws error> *** error WebSocket was closed before the connection was established
      - <ws connect error> *** WebSocket was closed before the connection was established
      - <ws disconnected> *** code=1006 reason=

```

**Comment by imartinflores** [comment]
Thanks @puagarwa  can see the tests running fine now. Appreciate a lot your help!

**Comment by imartinflores** [comment]
Hey @puagarwa I hope ur doing well, quick question, I am trying to get another project running and at the moment I am using an access token locally. I have added the URL and Token into my .env file, but when running the tests it comes up with:

The value for the PLAYWRIGHT_SERVICE_URL variable is not set correctly. Please verify the URL and try again.
Any suggestion where to look at ?

The url I am using is the following:
wss://westeurope.api.playwright.microsoft.com/accounts/westeurope_myId/browsers

This is my service config just in case:

```
import {
  getServiceConfig,
  ServiceOS,
} from "@azure/microsoft-playwright-testing";
import { defineConfig } from "@playwright/test";
import config from "./playwright.config";

/* Learn more about service configuration at https://aka.ms/mpt/config */
export default defineConfig(
  config,
  getServiceConfig(config, {
    exposeNetwork: "<loopback>",
    timeout: 30000,
    os: ServiceOS.LINUX,
    useCloudHostedBrowsers: true,
    serviceAuthType: "ACCESS_TOKEN",
  }),
  {
    /* 
    Playwright Testing service reporter is added by default.
    This will override any reporter options specified in the base playwright config.
    If you are using more reporters, please update your configuration accordingly.
    */
    reporter: [
      ["list"],
      [
        "html",
        {
          open: "never",
          outputFolder: "./tests/artefacts/playwright-tests/html-report",
        },276023
      ],
    ],
  },
);
```

**Comment by imartinflores** [comment]
@puagarwa yes, I deleted it, there was an error in the path of the config. Sorry for the inconvenience!

**Comment by puagarwa** [comment]
@imartinflores just in case you are not aware we have recently released reporting capabilities which you can enable by simply adding our reporter in playwright config file. Feel free to try out. 
['@azure/microsoft-playwright-testing/reporter']

https://learn.microsoft.com/en-us/azure/playwright-testing/quickstart-generate-rich-reports-for-tests?pivots=playwright-test-runner
