### ISSUE TITLE
[BUG]:Can't load the activity log

### ISSUE THREAD

**Issue by mike-taylor99** [microsoft/playwright-testing-service#154]
**Describe the bug**
Unable to load the activity log or view test report links when running on the playwright service

**To Reproduce**
View playwright service dashboard

**Expected behavior**
See runs and test reports that I have run

**Screenshots**
![Image](https://github.com/user-attachments/assets/c58af1fb-29b9-4df0-b99c-383cf9244021)

**Setup information (please complete the following information):**
 - Azure Subscription Id: 4dabc48d-ccda-4182-b789-2d8303fc12f0
 - Workspace Name: ExPUXE2EAME
 - Service trace Id (if available):
 - Log snippet (if available):
 - Browser on which tests are executed (if applicable): Edge
 - Time range (in PST) when the issue was experienced: 12/3/2024 12:45 - 3PM PST
 - Playwright Version: Latest
- Client machine OS: Windows 11 Enterprise (SAW)
- OS requested on Service: Linux

**Additional context**
Not sure if this is an issue on Playwright side or on my side. I have Owner role access for the subscription
Contact @mictaylor

**Comment by puagarwa** [comment]
Hi @mike-taylor99, I think you are trying to use AME tenant from secured machine, where one of our domain is not allowlisted. Allow us some time to allowlist it.

**Comment by puagarwa** [comment]
Hi @mike-taylor99 , We have completed the allowlisting and now it should work. please try.

**Comment by mike-taylor99** [comment]
Hi @puagarwa , thank you so much for the quick turnaround. I indeed am able to see the test runs and open the panel with the initial information and attachments for each test. I however am still encountering an issue when I try to view the stack trace for a test. Is this also AME related?
![Image](https://github.com/user-attachments/assets/d3a2b2dc-b7bb-4d3c-b691-711842b841d6)

**Comment by puagarwa** [comment]
@mike-taylor99 , yes this is known issue because trace.playwright.dev domain is not allowlisted in secure machine. This would take some time to get resolved as its not microsoft.com domain. 

Meanwhile, you can download the trace file in below manner and then browser trace.playwright.dev from non-secured machine and open the trace to proceed debugging.

How to download trace: 
Url looks like this in browser when you try open trace: https://playwright.microsoft.com/workspaces/XXX/runs/XXXX/tests/XXXX/trace?trace=https://.....
you can copy everything after "trace=" and open it in new tab, which should download the trace zip file locally. 

I will keep you updated on our progress to allowlist this domain.

**Comment by mike-taylor99** [comment]
Hi @puagarwa ,
I followed the steps mentioned above to download the stack trace and noticed that I can access the trace using the trace URL on my non-AME account. Could this be a potential SFI issue? The purpose of having this workspace on AME is to ensure that any sensitive data from our stack trace remains secure and isn’t easily accessible by others.

**Comment by puagarwa** [comment]
Hi @mike-taylor99 , 
    Your purpose to use AME account make sense, I am working with security team to allowlist it.

**Comment by mike-taylor99** [comment]
Hi @puagarwa,
Awesome! Thanks for working to allowlisting it on AME. I have a concern regarding the link that directly downloads the stack trace. Is there any restriction on who can download the trace file if they acquire the link? I’m worried this could pose a security vulnerability if the stack trace link accidentally falls into the wrong hands. One of our reasons for using the AME workspace was to control where information can be retrieved from, but I’m concerned that posting the direct stack trace download link might put us at risk since there’s no restriction on who can download it.

**Comment by puagarwa** [comment]
HI @mike-taylor99 ,
   
>> Is there any restriction on who can download the trace file if they acquire the link? 

Yes, the SAS url only generated when person can login into this portal using thier AME credential and have RBAC role, and then this SAS is valid for 1 hour from the time you generate it from our portal. Hence, it is safe.

Though, i agree getting this data out from Secure device may not be best security practice hence allowlisting this trace url would help so that you dont need to take it out of secure device.

**Comment by puagarwa** [comment]
HI @mike-taylor99 ,  Now the urls are allowlisted, you should be able to view trace from secure machine. please try and confirm.

**Comment by mike-taylor99** [comment]
Yes, it works now. Thank you so much for your help @puagarwa
