### ISSUE TITLE
Ability to access key vault and read secrets

### ISSUE THREAD

**Issue by chaitanya-cloudknox** [microsoft/playwright-testing-service#49]
**Is your feature request related to a problem? Please describe.**
Ability to read secrets in key vault using playwright service.

**Describe the solution you'd like**
On the service users can configure the key vault playwright service can access. And the tests can read credentials from the key vault.

**Describe alternatives you've considered**
Today we are using msal to login and access the secrets from key vault. 

AB#1893484

**Comment by chaitanya-cloudknox** [comment]
Hi @puagarwa,
* We would like to access usernames and passwords for different roles for a cell/region for login.
* In Client we are using env variables for usernames and passwords. The ask is for CI, Currently we are using preconfigured azure CLI in our jenkins machine to read the credentials from key vault and use them in the tests using environment variables and We think it would be better if we can access through playwright service.
*  If an api is avilable from playwright, we could configure the Playwright service config to use those credentials

**Comment by puagarwa** [comment]
First thing, I acknowledge that its good problem to solve. 
Would your ask be fulfilled if CI providers provide better way to directly fetch secrets from Key Vault so that you dont need to use CLI to fetch secrets and put it into CI variables ? 

I did quick search and found Azure pipeline has good way https://learn.microsoft.com/en-us/azure/devops/pipelines/release/azure-key-vault?view=azure-devops&tabs=yaml
and found something in jenkins as well but not sure whether it fits the need https://plugins.jenkins.io/azure-keyvault/

As with service, problem is two fold: 1. playwright config/API support this KV integration as well as 2. service browser need to be able to access KV which need managed identity based permission, while 2nd is something we will consider in future but 1st is out of scope from service side.

**Comment by chaitanya-cloudknox** [comment]
Thank you for sharing the Azure Pipeline docs. We will eventually move to Azure pipeline but we will be using Jenkins for at least year.

**Comment by puagarwa** [comment]
@chaitanya-cloudknox Do you feel if jenkins has a similar way to link secret variable with KV, that would cater to your need?  if yes then i would suggest closing this issue.
