### ISSUE TITLE
[BUG]:[Error: No Tests found]

### ISSUE THREAD

**Issue by Kranael** [microsoft/playwright-testing-service#61]
**Describe the bug**
Followed the guideline in playwright.microsoft.com/workspaces/westeurope_{id} -> named: Let's run your first test in the cloud

**To Reproduce**
1. Step 1 followed all steps
2. Step 2 used a existing playwright project that we used for PoC
3. Step 3 it contain only api tests no ui tests
4. Step 4 run the command npx playwright test --config=playwright.service.config.ts --workers=20

**Expected behavior**
The test_dir is loaded from the playwright.config.ts
All tests are found and running
the result that I get local instead I get in the cloud

**Actual behavior**
Error: No tests found

**Screenshots**
![Snag_1a22bbd1](https://github.com/microsoft/playwright-testing-service/assets/55143610/ce24f8f3-91e9-44e4-9afa-60d99644abc1)
![Snag_1a28c1cf](https://github.com/microsoft/playwright-testing-service/assets/55143610/f1d9b02b-8687-472a-8a35-ffb730bb28d2)

**Setup information (please complete the following information):**
 - Azure Subscription Id: dbb155d0-5305-4590-9b32-9993265bbd14
 - Workspace Name: TestautomationCIP

 - Service trace Id (if available):
 - Log snippet (if available):
 - Browser on which tests are executed (if applicable): nothing because we use just REST API testing
 - Time range (in PST) when the issue was experienced:
 - Playwright Version: 1.39.0
- Client machine OS: Windows
- OS requested on Service: linux

**Additional context**
Is it not possible to test REST apis with this service?

AB#1906945

**Comment by puagarwa** [comment]
@Kranael First of all, API test is not fit for service as service provide browser in cloud which your API test doesnt need anyway, hence you dont need service. You could simply increase worker count and run your test locally with more parallelism. 

Coming back to above No Test found issue: This is strange and shouldnt have happened as this is not related to service being used or not. I guess its due to configuration issue and most possible reason is wrong test directory. you could check it or share your both config file with me.

**Comment by puagarwa** [comment]
@Kranael Just checking if you get chance to look into above response and try it out. Let me know if you need any help.

**Comment by puagarwa** [comment]
closing the issue but feel free to reopen it if need any help.
