### ISSUE TITLE
[BUG]:Failed to launch browser playwright service without installing chromium locally

### ISSUE THREAD

**Issue by lxy2222** [microsoft/playwright-testing-service#68]
**Describe the bug**

**To Reproduce**
1.  Setup pipeline running playwright on ADO
2.  Execute the command "npx playwright test _Test_CASE_Folder  --config=playwright.service.config.new.ts
4. See errors

**Expected behavior**
The browser can launch, and the test can work

**Screenshots**
the pipeline link  https://office.visualstudio.com/OC/_build/results?buildId=24007594&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=5fd232ee-0bcd-5c4f-9e6b-7e96853085e6
Also, the config file is:
https://office.visualstudio.com/OC/_git/Forms-Automation?path=/playwright.service.config.new.ts
![image](https://github.com/microsoft/playwright-testing-service/assets/12553152/98d76ec5-ed6f-4695-a06e-c096840e808e)
 

**Setup information (please complete the following information):**
 - Azure Subscription Id:ac8443ed-88f1-40e5-beb9-2e875d6cd24f
 - Workspace Name:FormsPlaywrightWorkSpace
 - Service trace Id (if available):
 - Log snippet (if available):
 - Browser on which tests are executed (if applicable):chromium
 - Time range (in PST) when the issue was experienced:
 - Playwright Version:1.39
- Client machine OS:linux
- OS requested on Service:

**Additional context**

AB#1912711

**Comment by puagarwa** [comment]
Hi @lxy2222 ,
  I looked into your codebase and figured out below
- In globalSetup, you are doing browser.launch hence you wont be using service browser hence as per above error, you need to install browsers. installing browsers should unblock you.
- since you only open single browser in global setup, its ok to use local browser.
- However, you could migrate to new way of [global setup](https://playwright.dev/docs/test-global-setup-teardown#option-1-project-dependencies) which uses project dependencies and that will use service browser automatically. 
-  Minor thing, I noticed in your global setup, you are only stopping tracing in exception case, you should stop it even in success case as well or put it inside finally.

**Comment by lxy2222** [comment]
Thanks @puagarwa for detailed clarification.
We replaced the browser.launch with browser.connect when enabling service. And it works
