### ISSUE TITLE
Scaling API tests using Playwright .NET tests with Microsoft Playwright Testing

### ISSUE THREAD

**Issue by christiannagel** [microsoft/playwright-testing-service#93]
Should it be possible to run multiple tests at once using .NET tests?

I used this information to run the tests:
https://github.com/microsoft/playwright-testing-service/

Tests are running, but I just could make it to run a max of 4 games in parallel. I expected a lot more with up to 50 workers. What did I miss?

My test project is here - in the ch12-scaling branch:
https://github.com/PacktPublishing/Pragmatic-Microservices-with-CSharp-and-Azure/tree/12-scaling/ch12/Codebreaker.GameAPIs.Playwright

Thanks!

AB#1951029

**Comment by puagarwa** [comment]
Hi @christiannagel There are two things i want to highlight 
- I looked into your test project and it uses APIRequest which doesnt need browser hence you dont need to use MPT service, even though you might have followed our doc to integrate service but as your test project doesnt launch browser, it doesnt consume service.
- Coming back parallelisation in Nunit framework, please follow this https://docs.nunit.org/articles/nunit/writing-tests/attributes/parallelizable.html and https://docs.nunit.org/articles/vs-test-adapter/Tips-And-Tricks.html#numberoftestworkers. Most likely reason why you are able to use only 4 worker is because you are using default worker setting which configure worker count based on cores. You can override it.

**Comment by puagarwa** [comment]
@christiannagel MPT service is when you need browsers, mostly its the case with Browser Tests for web applications. 

Yes, Azure Load Testing would serve better here if you want to do API load testing. I dont think it would work directly with NUnit suite but rather you need to have jmeter suite.

**Comment by christiannagel** [comment]
@puagarwa thanks a lot!
